### ISSUE TITLE
report_statuses, default value: documentation vs actual logic

### ISSUE THREAD

**Issue by petski** [bigpresh/Bot-BasicBot-Pluggable-Module-Nagios#1]
Documenation for "report_statuses" says that default for "report_statuses" is "CRITICAL, OK":

> List of statuses we should notify for (default: CRITICAL, OK)

But, on the contrary, the perl-code says:

``` perl
my $report_statuses = $self->get('report_statuses') || [ qw( CRITICAL WARNING OK ) ];
```

I'm willing to supply a (mini)patch if you would let me know what the desired behaviour is :)

**Comment by bigpresh** [comment]
... I'm really sorry it's taken me so long to reply to this.  I suck.

I *think* the default should be all of them, including WARNING; for anyone who finds warning statuses to result in excessive noise, they can easily disable them via that setting, but setting it to ignore WARNING by default could confuse people who didn't expect that.

I'll tweak the doco in a sec - thank you very much for reporting it, and sorry for the HUGE delay!
